#!/bin/sh

export LD_LIBRARY_PATH=/oem/usr/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

case "$1" in
    start) /oem/usr/bin/fr-ai-service.sh start ;;
    stop) /oem/usr/bin/fr-ai-service.sh stop ;;
    restart) /oem/usr/bin/fr-ai-service.sh restart ;;
esac
